#!/usr/bin/python

import unittest
#from smugmugalbums import *
from smugmugcategory import *
#from smugmugimages import *
import smugmugglobals

smugmugglobals.smugmughandler = "test"

class SmugCategoryTests(unittest.TestCase):

  category_mock = {'id':1234,'Name':'namename', 'NiceName':'nicenice', 'Type':"type"}

  category = SmugMugCategory( category_mock )

  def test_init(self):
    self.assertEqual(self.category.id, 1234)
    self.assertEqual(self.category.name, 'namename')
    self.assertEqual(self.category.nicename, 'nicenice')
    self.assertEqual(self.category.type, 'type' )
    self.assertEqual( len(self.category_mock), 4 )

unittest.main()
  



