#!/usr/bin/python

import unittest
from smugmugalbums import *
from smugmugcategories import *

  class SmugTests(unittest.TestCase):
    def test_category_create(self):
      

          def test_average(self):
                     self.assertEqual(average([20, 30, 70]), 40.0)
                                self.assertEqual(round(average([1, 5, 7]), 1), 4.3)
                                           self.assertRaises(ZeroDivisionError, average, [])
                                                      self.assertRaises(TypeError, average, 20, 30, 70)

                                                         unittest.main() # Calling from the command line invokes all tests

from unittest import * 


album = SmugMugAlbum()
album.create( "title" )
album.delete( "ID" )
album.getInfo( "ID", "key")
album.get()
album.changeSettings("ID")
album.comments_add()
album.comments_get()

category=SmugMugCategory()
status, cat = category.create("name")
TestCase.assertEqual(status, "ok" )
  



