#!/bin/bash

i=1
res=""

cat $1 | grep -vi "(required)" | cut -f 1-2 -d " " > ${1}.clean
while read a b; 
do 
  f="'$a' : '$b'"

  if [ $i == 1 ]; then
    res=$f
  else
    res="$res, $f"
  fi
  i=2
done < ${1}.clean

echo $res
