#!/usr/bin/python

import unittest
from smugmugalbums import *
from smugmugcategories import *
from smugmugimages import *

class SmugCategoryTests(unittest.TestCase):
  category = SmugMugCategory()

  def test_create(self):
    status, cat = self.category.create("name")
    self.assertEqual(status, "ok" )
    self.assertEqual(cat['id'], 1234)

  def test_delete(self):
    ret = self.category.delete(123)
    self.assertEqual(ret, "ok")

  def test_get(self):
    status, categories = self.category.get()
    self.assertEqual(status, "ok")
    self.assertEqual(type(categories), list)
    
  def test_rename(self):
    ret = self.category.rename( 123, "name")
    self.assertEqual(ret, "ok")

class SmugAlbumTests(unittest.TestCase):
  album = SmugMugAlbum()

  def test_create(self):
    stat, alb = self.album.create("title")
    self.assertEqual(stat, "ok")
    self.assertEqual(type(alb), dict)
    self.assertEqual(alb['id'], 1234)

  def test_delete(self):
    ret = self.album.delete(123)
    self.assertEqual(ret, 'ok')


class SmugImageTests(unittest.TestCase):
  image=SmugMugImage()
  def test_get(self):
    stat, alb, images = self.image.get(123, 'asd')
    self.assertEqual(type(images), list)
unittest.main()
  



